import { PlaceholderProduct } from '@/types';

export const placeholderProducts: PlaceholderProduct[] = [
  {
    id: 'p1',
    handle: 'pina-colada-slushi',
    title: 'Piña Colada Slushi',
    description: 'Tropical paradise in every sip. Creamy coconut meets sweet pineapple in a perfectly frozen blend.',
    price: '6.99',
    currencyCode: 'USD',
    category: 'slushies',
    image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600&q=80',
    flavor: 'Tropical',
    ingredients: ['Pineapple', 'Coconut Cream', 'Lime', 'Ice'],
    tags: ['slushi', 'tropical', 'bestseller'],
    variantId: 'variant-p1',
  },
  {
    id: 'p2',
    handle: 'strawberry-slushi',
    title: 'Strawberry Bliss Slushi',
    description: 'Intensely sweet, perfectly tart. Made with hand-picked strawberries and crushed himalayan ice.',
    price: '5.99',
    currencyCode: 'USD',
    category: 'slushies',
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=600&q=80',
    flavor: 'Berry',
    ingredients: ['Strawberry', 'Lemon Juice', 'Sugar Cane', 'Ice'],
    tags: ['slushi', 'berry', 'popular'],
    variantId: 'variant-p2',
  },
  {
    id: 'p3',
    handle: 'mango-smoothie',
    title: 'Mango Sunrise Smoothie',
    description: 'Velvety smooth with a golden sunset color. Packed with vitamins and natural mango sweetness.',
    price: '7.49',
    currencyCode: 'USD',
    category: 'smoothies',
    image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=600&q=80',
    flavor: 'Tropical',
    ingredients: ['Mango', 'Banana', 'Orange Juice', 'Ginger'],
    tags: ['smoothie', 'tropical', 'vegan'],
    variantId: 'variant-p3',
  },
  {
    id: 'p4',
    handle: 'green-detox-juice',
    title: 'Green Detox Juice',
    description: 'Nature\'s most powerful cleanse. Cold-pressed spinach, cucumber and green apple for pure vitality.',
    price: '8.99',
    currencyCode: 'USD',
    category: 'natural-juices',
    image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=600&q=80',
    flavor: 'Green',
    ingredients: ['Spinach', 'Cucumber', 'Green Apple', 'Celery', 'Lemon'],
    tags: ['juice', 'detox', 'vegan', 'cold-pressed'],
    variantId: 'variant-p4',
  },
  {
    id: 'p5',
    handle: 'chocolate-milkshake',
    title: 'Premium Chocolate Shake',
    description: 'Indulgent, rich and impossibly smooth. Belgian chocolate meets premium ice cream in this showstopper.',
    price: '9.99',
    currencyCode: 'USD',
    category: 'milkshakes',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&q=80',
    flavor: 'Chocolate',
    ingredients: ['Belgian Chocolate', 'Vanilla Ice Cream', 'Whole Milk', 'Whipped Cream'],
    tags: ['milkshake', 'chocolate', 'indulgent'],
    variantId: 'variant-p5',
  },
  {
    id: 'p6',
    handle: 'protein-berry-cup',
    title: 'Protein Berry Power Cup',
    description: 'Fuel your body the delicious way. 30g protein, mixed berries and superfoods in one powerful cup.',
    price: '11.99',
    currencyCode: 'USD',
    category: 'protein-cups',
    image: 'https://images.unsplash.com/photo-1638176066959-e6a7e8f18b55?w=600&q=80',
    flavor: 'Berry',
    ingredients: ['Whey Protein', 'Mixed Berries', 'Almond Milk', 'Chia Seeds', 'Honey'],
    tags: ['protein', 'fitness', 'healthy'],
    variantId: 'variant-p6',
  },
  {
    id: 'p7',
    handle: 'tropical-fruit-cup',
    title: 'Tropical Fruit Cup',
    description: 'A feast of premium exotic fruits, freshly cut and served in a signature himalaya cup.',
    price: '7.99',
    currencyCode: 'USD',
    category: 'fruit-cups',
    image: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&q=80',
    flavor: 'Tropical',
    ingredients: ['Watermelon', 'Mango', 'Pineapple', 'Papaya', 'Lime Zest'],
    tags: ['fruit', 'fresh', 'healthy'],
    variantId: 'variant-p7',
  },
  {
    id: 'p8',
    handle: 'blueberry-slushi',
    title: 'Blueberry Frost Slushi',
    description: 'Deep purple perfection. Wild blueberries blended with lemon zest into a luminous icy experience.',
    price: '6.49',
    currencyCode: 'USD',
    category: 'slushies',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a90a3102?w=600&q=80',
    flavor: 'Berry',
    ingredients: ['Wild Blueberry', 'Lemon', 'Vanilla', 'Ice'],
    tags: ['slushi', 'berry', 'antioxidant'],
    variantId: 'variant-p8',
  },
  {
    id: 'p9',
    handle: 'fresh-fruit-plate',
    title: 'Fresh Cut Fruit Platter',
    description: 'Artfully arranged seasonal fruits, hand-cut to order. Served with our signature chamoy dip.',
    price: '12.99',
    currencyCode: 'USD',
    category: 'fresh-cut-fruit',
    image: 'https://images.unsplash.com/photo-1490885578174-acda8905c2c6?w=600&q=80',
    flavor: 'Seasonal',
    ingredients: ['Seasonal Fruits', 'Tajin', 'Chamoy', 'Lime Juice'],
    tags: ['fresh', 'sharing', 'seasonal'],
    variantId: 'variant-p9',
  },
  {
    id: 'p10',
    handle: 'rainbow-mix-slushi',
    title: 'Rainbow Mix Slushi',
    description: 'Seven flavors swirled into one spectacular icy masterpiece. The signature HIMALAYA experience.',
    price: '8.49',
    currencyCode: 'USD',
    category: 'slushies',
    image: 'https://images.unsplash.com/photo-1561506083-b2f71f04dbe9?w=600&q=80',
    flavor: 'Mixed',
    ingredients: ['Strawberry', 'Mango', 'Lime', 'Blueberry', 'Peach', 'Watermelon', 'Coconut'],
    tags: ['slushi', 'signature', 'rainbow', 'bestseller'],
    variantId: 'variant-p10',
  },
  {
    id: 'p11',
    handle: 'peach-smoothie',
    title: 'Peach Velvet Smoothie',
    description: 'Silky and sweet with notes of vanilla. Georgia peaches meet premium yogurt for a luxurious blend.',
    price: '7.99',
    currencyCode: 'USD',
    category: 'smoothies',
    image: 'https://images.unsplash.com/photo-1619898804176-0a1fefc28c2e?w=600&q=80',
    flavor: 'Peach',
    ingredients: ['Georgia Peach', 'Greek Yogurt', 'Vanilla', 'Honey', 'Almond Milk'],
    tags: ['smoothie', 'peach', 'creamy'],
    variantId: 'variant-p11',
  },
  {
    id: 'p12',
    handle: 'green-apple-slushi',
    title: 'Green Apple Slushi',
    description: 'Crisp, tart and electrifyingly refreshing. Real Granny Smith apples crushed into icy perfection.',
    price: '5.99',
    currencyCode: 'USD',
    category: 'slushies',
    image: 'https://images.unsplash.com/photo-1603569283847-aa295f0d016a?w=600&q=80',
    flavor: 'Apple',
    ingredients: ['Green Apple', 'Lime', 'Mint', 'Ice'],
    tags: ['slushi', 'apple', 'refreshing'],
    variantId: 'variant-p12',
  },
];

export const categoryMeta: Record<string, { label: string; icon: string; gradient: string }> = {
  slushies:        { label: 'Slushies',             icon: '🧊', gradient: 'from-blue-500 to-cyan-400' },
  smoothies:       { label: 'Smoothies',             icon: '🥤', gradient: 'from-orange-400 to-yellow-300' },
  'natural-juices':{ label: 'Natural Juices',        icon: '🍊', gradient: 'from-green-400 to-emerald-300' },
  milkshakes:      { label: 'Milkshakes',            icon: '🍦', gradient: 'from-pink-400 to-rose-300' },
  'protein-cups':  { label: 'Protein Cups',          icon: '💪', gradient: 'from-purple-500 to-violet-400' },
  'fruit-cups':    { label: 'Fruit Cups',            icon: '🍓', gradient: 'from-red-400 to-pink-300' },
  'fresh-cut-fruit':{ label: 'Fresh Cut Fruit',      icon: '🍉', gradient: 'from-emerald-400 to-teal-300' },
};
